/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ArticleDesk": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "AuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DirectUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NodeEnv": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}